### PR TITLE
Fix option to reuse an existing key pair

### PR DESCRIPTION
**Pull request by ampaze**
This fixes my previous pull request #11, check there for details.

### CODE REVIEW

**Comment by ampaze** [comment]
@ptrstovka Have you abandoned this repository? 😢

**Comment by ptrstovka** [comment]
Hi. Sorry for the delay but unforunatelly I cannot longer maintain this repository and I am considering archiving it. I'm no more using it and to keep up with Let's encrypt changes it requires active reviewing of changes made by Let's encrypt and integrating them to the library. If you feel you can continue supporting this library I am more than open to transfer the ownership of the repository.

**Comment by ampaze** [comment]
Sorry for the late response, I was on vacation.

We are still actively using this code, let me think about if I should take over this repo or just use my fork.

Thanks for your work.

**Comment by ampaze** [comment]
Okay, I will just use my fork for the time being. You can go ahead and mark the repository as abandoned. Thanks again for having created this in the first place.

**Pull request closed without merging**
